### ISSUE TITLE
Building the acerules-server

### ISSUE THREAD

**Issue by michael-aquilina** [tkuhn/AceRules#1]
Hi,

I'm unable to execute the acerules-server.exe generated by the compile_webservice.sh . It is not showing any errors while generating, but when trying to run the file i get "the file or directory is corrupted and unreadable". I am using the following setup:

- ape-6.7-131003
- SWI-Prolog version 7.6.4 for x64-win64
- Windows 10

Can you point me in the right direction to get the file  running?

**Comment by tkuhn** [comment]
Hi,

You have to execute it in a Unix environment. The .exe extension is confusing (sorry for that), but it's just a plain Unix executable and not a Windows one. So, under Windows, you probably need to run a virtual machine with Linux, or Cygwin might work too.

Cheers,
Tobias

**Comment by tkuhn** [comment]
Assuming this is resolved.
