### ISSUE TITLE
Web version broken

### ISSUE THREAD

**Issue by Piratux** [tkuhn/AceRules#2]
Hello,
I found this [page](https://www.swi-prolog.org/pack/file_details/logicmoo_nlu/ext/AceRules/webapp/war/index.html) which has a link named [AceRules Web Interface](https://www.swi-prolog.org/pack/file_details/logicmoo_nlu/ext/AceRules/webapp/war/interface).

However, trying to open the link, shows the following (error?) message:

![image](https://github.com/user-attachments/assets/7c1ce5f8-a05b-4c01-9a60-36a43d1d343a)

Is it possible to use AceRules tool online somewhere else instead?
For reference, it would be great if there was a way to use AceRules like in this [Demo Video](http://attempto.ifi.uzh.ch/site/docs/screencast_acerules.mov)

**Comment by tkuhn** [comment]
Not sure about the link you are referring to, but AceRules used to be available here (now broken): http://attempto.ifi.uzh.ch/acerules/

We are working to get these services up again, but it might take a bit.

In the meantime, I added instructions on how to run AceRules locally with Docker: https://github.com/tkuhn/AceRules

I hope that helps.

**Comment by Piratux** [comment]
Thank you for your quick response.

For now, I have found [RACE tool](http://attempto.ifi.uzh.ch/race/) available online, which allows me to verify textual reasoning and that fits my needs.

Thanks.

**Comment by tkuhn** [comment]
Great to hear! Closing this, then.
